# Generated by Django 2.1.5 on 2019-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='College_name',
            field=models.TextField(default='sd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='email',
            field=models.EmailField(default='asd', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='phone',
            field=models.TextField(default='ss', max_length=100),
            preserve_default=False,
        ),
    ]
